apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "text-generation-inference-benchmark.fullname" . }}-nginx-config
data:
  default: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  localhost;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        autoindex on;
      }

      error_page   500 502 503 504  /50x.html;
        location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }