apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference-benchmarker.fullname" . }}
  labels:
    app.kubernetes.io/component: text-generation-inference
    {{- include "inference-benchmarker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: text-generation-inference
    {{- include "inference-benchmarker.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference-benchmarker.fullname" . }}-benchmark
  labels:
    app.kubernetes.io/component: benchmark
    {{- include "inference-benchmarker.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/component: benchmark
    {{- include "inference-benchmarker.selectorLabels" . | nindent 4 }}
